apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingclient-deployment
  labels:
    app: shoppingclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoppingclient
  template:
    metadata:
      labels:
        app: shoppingclient
    spec:
      containers:
        - name: shoppingclient
          image: acrshoppingrmoreiraowe.azurecr.io/shopping/shopping-web-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ShoppingAPIUrl
              valueFrom:
                configMapKeyRef:
                  name: shoppingapi-configmap
                  key: shoppingapi_url
          resources:
            requests:
              memory: 64Mi
              cpu: 200m
            limits:
              memory: 128Mi
              cpu: 400m
      # imagePullSecrets:
      #       - name: acr-pull
---
apiVersion: v1
kind: Service
metadata:
  name: shoppingclient-service
spec:
  # For test purpose, set to NodePort
  type: LoadBalancer
  selector:
    app: shoppingclient
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: shoppingclient-hpa
spec:
  maxReplicas: 10 # define max replica count
  minReplicas: 2  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shoppingclient-deployment
  targetCPUUtilizationPercentage: 50 # target CPU utilization