# Use 

apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  # Values are in Base64, so use this to convert: https://base64.guru/converter
  # user: root
  mongo-root-username: cm9vdA==
  # pass: example
  mongo-root-password: ZXhhbXBsZQ==