apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:4.4.6
          ports:
            - containerPort: 27017
          resources:
            requests: 
              memory: 64Mi
              cpu: 250m
            limits:
              memory: 128Mi
              cpu: 500m            
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
# Use 

apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  # Values are in Base64, so use this to convert: https://base64.guru/converter
  # user: root
  mongo-root-username: {{.Values.db.user_base64}}
  # pass: example
  mongo-root-password: {{.Values.db.password_base64}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-configmap
data:
  connection_string: mongodb://{{.Values.db.user}}:{{.Values.db.password}}@mongodb-service:27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingapi-deployment
  labels:
    app: shoppingapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoppingapi
  template:
    metadata:
      labels:
        app: shoppingapi
    spec:
      containers:
        - name: shoppingapi
          image: acrshoppingrmoreiraowe.azurecr.io/shopping/shopping-api:{{.Values.image.tag}}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: DatabaseSettings__ConnectionString
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: connection_string
          resources:
            requests:
              memory: 64Mi
              cpu: 200m
            limits:
              memory: 128Mi
              cpu: 400m
---
apiVersion: v1
kind: Service
metadata:
 name: shoppingapi-service
spec:
  # For test purpose, set to NodePort
  selector:
    app: shoppingapi
  ports:
    - protocol: TCP
      port: 80


# apiVersion: v1
# kind: Service
# metadata:
#   name: shoppingapi-service
# spec:
#   # For test purpose, set to NodePort
#   type: LoadBalancer
#   selector:
#     app: shoppingapi
#   ports:
#     - protocol: TCP
#       port: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: shoppingapi-hpa
spec:
  maxReplicas: 10 # define max replica count
  minReplicas: 2  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shoppingapi-deployment
  targetCPUUtilizationPercentage: 50 # target CPU utilization
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shoppingapi-configmap
data:
  shoppingapi_url: http://shoppingapi-service
