name: Build and deploy Web App
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        
        - name: Log in with Azure
          uses: Azure/login@v1
          with:
            # CLIENT_ID = Client ID of Service  Principal
            # CLIENT_SECRET = Password created for this specific connection - this can further enhanced
            creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'

        - name: Build POI Web docker image
          working-directory: Shopping
          run:  az acr build --image shopping/shopping-web-app:latest  --registry acrshoppingrmoreiraowe --build-arg build_version=latest --file Shopping.Client/Dockerfile .

  deploy:
    runs-on: ubuntu-latest
    needs: build
      
    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.WEB_APP_NAME }}
          images: '${{ secrets.ACR_URL }}/shopping/shopping-web-app:latest'
