name: Build and deploy API
on:
  push:
    branches: [ "main" ]
    paths: 
      - 'Shopping/Shopping.API/**'
    
  workflow_dispatch:
  
jobs:
  
  build_deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        
        - name: Log in with Azure
          uses: Azure/login@v1
          with:
            # CLIENT_ID = Client ID of Service  Principal
            # CLIENT_SECRET = Password created for this specific connection - this can further enhanced
            creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'

        - name: Build docker image and push to ACR
          working-directory: Shopping
          run:  az acr build --image shopping/shopping-api:latest  --registry acrshoppingrmoreiraowe --build-arg build_version=latest --file Shopping.API/Dockerfile .

        # - name: Deploy API
        #   id: deploy-to-webapp
        #   uses: azure/webapps-deploy@v2
        #   with:
        #     app-name: ${{ secrets.API_APP_NAME }}
        #     images: '${{ secrets.ACR_URL }}/shopping/shopping-api:latest'
