name: Build and deploy API
on:
  # Default pipeline for the Shopping API is the heml pipeline
  # push:
  #   branches: [ "main" ]
  #   paths: 
  #     - 'Shopping/Shopping.API/**'
  #     - 'aks/shoppingapi.yaml'
      
  workflow_dispatch:

env:
  environment: 'prod'
  rgName: rg-shoppingwebapprmoreirao-prod-${{ secrets.LOCATION_SUFFIX }}
  AKS_CLUSTER_NAME: aks-shoppingrmoreirao-prod-${{ secrets.LOCATION_SUFFIX }}
  AZURE_CONTAINER_REGISTRY: acrshoppingrmoreiraowe

jobs:
  
  build_deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        
        - name: Log in with Azure
          uses: Azure/login@v1
          with:
            # CLIENT_ID = Client ID of Service  Principal
            # CLIENT_SECRET = Password created for this specific connection - this can further enhanced
            creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'

        - name: Build Shopping API docker image and push to ACR
          working-directory: Shopping
          run:  az acr build --image shopping/shopping-api:${{ github.sha }}  --registry acrshoppingrmoreiraowe --build-arg build_version=${{ github.sha }} --file Shopping.API/Dockerfile .

         # Retrieves your Azure Kubernetes Service cluster's kubeconfig file
        - name: Get K8s context
          uses: azure/aks-set-context@v3
          with:
            resource-group: ${{ env.rgName }}
            cluster-name: ${{ env.AKS_CLUSTER_NAME }}

         # Deploys application based on given manifest file
        - name: Deploys application
          uses: Azure/k8s-deploy@v4
          with:
            action: deploy
            manifests: |
              aks/shoppingapi.yaml
            images: |
              ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/shopping/shopping-api:${{ github.sha }}