# This is a basic workflow to help you get started with Actions

name: IaC CICD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    paths: 
      - 'iac/**'
  workflow_dispatch:

env:
  environment: 'prod'
  rgName: rg-shoppingwebapprmoreirao-$environment-${{ secrets.LOCATION_SUFFIX }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  CI_CD:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Log in with Azure
        uses: Azure/login@v1
        with:
          # CLIENT_ID = Client ID of Service Principal
          # CLIENT_SECRET = Password created for this specific connection - this can further enhanced
          creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'

      - name: Create Resource Group
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az account set --subscription ${{ secrets.SUBSCRIPTION_ID }}
            az group create --name ${{ env.rgName }} --location ${{ secrets.LOCATION }}


      # Runs a single command using the runners shell
      - name: Run bicep lint
        working-directory: iac/
        run: az bicep build --file main.bicep
    
      - name: Run bicep validation
        working-directory: iac/
        run: az deployment group validate --name "Validate" --resource-group ${{ env.rgName }} --template-file main.bicep --parameters location_suffix="${{ secrets.LOCATION_SUFFIX }}" environment="${{ env.environment }}"

      - name: Run bicep preview
        working-directory: iac/
        run: az deployment group what-if --name "Preview" --resource-group ${{ env.rgName }}  --template-file main.bicep  --parameters location_suffix="${{ secrets.LOCATION_SUFFIX }}" environment="${{ env.environment }}"

      - name: Deploy bicep
        working-directory: iac/
        run: az deployment group create --name "Deploy" --resource-group ${{ env.rgName }}  --template-file main.bicep  --parameters location_suffix="${{ secrets.LOCATION_SUFFIX }}" environment="${{ env.environment }}" 